version: '3'
services:
  ws-rest:
    image: pragusga/eews:ws-rest-v1
    container_name: ws-rest
    environment:
      - BOOTSTRAP_SERVERS=<ip-kafka1>:<port-kafka1>,<ip-kafka2>:<port-kafka2>
      - TOPIC_CONSUMERS=p_arrival,pick
      - PORT=8083
      - PRODUCER_SERVICE=http://<ip-producer>:<port-producer>
      - REDIS_HOST=<ip-redis>:<port-redis>
      - REDIS_PASSWORD=<redis-port>
    ports:
      - '80:8083'
